import type {
  Employee,
  Admin,
  LoanRequest,
  Transaction,
  SalaryRecord,
  AnalyticsData,
} from "./types";

export const mockEmployees: Employee[] = [
  {
    id: "emp-001",
    employeeId: "EMP001",
    name: "Sokha Chan",
    email: "sokha@company.com",
    role: "EMPLOYEE",
    department: "Engineering",
    position: "Senior Developer",
    joinDate: "2022-03-15",
    salary: 3500,
    walletBalance: 1200,
    financialHealthScore: 85,
    attendanceRate: 96,
    riskScore: 88,
    badge: "Excellent",
  },
  {
    id: "emp-002",
    employeeId: "EMP002",
    name: "Dara Kim",
    email: "dara@company.com",
    role: "EMPLOYEE",
    department: "Marketing",
    position: "Marketing Lead",
    joinDate: "2021-07-20",
    salary: 2800,
    walletBalance: 800,
    financialHealthScore: 72,
    attendanceRate: 89,
    riskScore: 65,
    badge: "Good",
  },
  {
    id: "emp-003",
    employeeId: "EMP003",
    name: "Vanna Pich",
    email: "vanna@company.com",
    role: "EMPLOYEE",
    department: "Sales",
    position: "Sales Representative",
    joinDate: "2023-01-10",
    salary: 2200,
    walletBalance: 350,
    financialHealthScore: 48,
    attendanceRate: 78,
    riskScore: 42,
    badge: "Poor",
  },
  {
    id: "emp-004",
    employeeId: "EMP004",
    name: "Leap Seng",
    email: "leap@company.com",
    role: "EMPLOYEE",
    department: "Finance",
    position: "Accountant",
    joinDate: "2020-11-05",
    salary: 3000,
    walletBalance: 2100,
    financialHealthScore: 91,
    attendanceRate: 98,
    riskScore: 92,
    badge: "Excellent",
  },
  {
    id: "emp-005",
    employeeId: "EMP005",
    name: "Chenda Mao",
    email: "chenda@company.com",
    role: "EMPLOYEE",
    department: "HR",
    position: "HR Specialist",
    joinDate: "2022-09-01",
    salary: 2600,
    walletBalance: 600,
    financialHealthScore: 60,
    attendanceRate: 85,
    riskScore: 55,
    badge: "Fair",
  },
  {
    id: "emp-006",
    employeeId: "EMP006",
    name: "Srey Neth",
    email: "srey@company.com",
    role: "EMPLOYEE",
    department: "Engineering",
    position: "Junior Developer",
    joinDate: "2024-02-15",
    salary: 1800,
    walletBalance: 200,
    financialHealthScore: 55,
    attendanceRate: 92,
    riskScore: 60,
    badge: "Fair",
  },
  {
    id: "emp-007",
    employeeId: "EMP007",
    name: "Sophal Rin",
    email: "sophal@company.com",
    role: "EMPLOYEE",
    department: "Operations",
    position: "Operations Manager",
    joinDate: "2019-06-20",
    salary: 3800,
    walletBalance: 3200,
    financialHealthScore: 95,
    attendanceRate: 99,
    riskScore: 95,
    badge: "Excellent",
  },
  {
    id: "emp-008",
    employeeId: "EMP008",
    name: "Raksa Tep",
    email: "raksa@company.com",
    role: "EMPLOYEE",
    department: "Sales",
    position: "Sales Manager",
    joinDate: "2021-04-12",
    salary: 3200,
    walletBalance: 450,
    financialHealthScore: 38,
    attendanceRate: 75,
    riskScore: 35,
    badge: "Poor",
  },
];

// ── Admin ────────────────────────────────────────────────────
export const mockAdmin: Admin = {
  id: "admin-001",
  name: "Bopha Keo",
  email: "bopha@company.com",
  role: "ADMIN",
  department: "Management",
  position: "HR Director",
  joinDate: "2018-01-10",
};

// ── Loans ────────────────────────────────────────────────────
export const mockLoans: LoanRequest[] = [
  {
    id: "loan-001",
    employeeId: "emp-001",
    employeeName: "Sokha Chan",
    department: "Engineering",
    amount: 1000,
    reason: "Medical emergency",
    requestDate: "2025-12-01",
    status: "completed",
    riskScore: 88,
    riskLevel: "low",
    repaymentMonths: 3,
    monthlyDeduction: 333.33,
    remainingBalance: 0,
    approvedDate: "2025-12-01",
    approvedBy: "System (Auto-Approved)",
  },
  {
    id: "loan-002",
    employeeId: "emp-002",
    employeeName: "Dara Kim",
    department: "Marketing",
    amount: 800,
    reason: "Home repair",
    requestDate: "2026-01-15",
    status: "repaying",
    riskScore: 65,
    riskLevel: "medium",
    repaymentMonths: 4,
    monthlyDeduction: 200,
    remainingBalance: 400,
    approvedDate: "2026-01-16",
    approvedBy: "Bopha Keo",
  },
  {
    id: "loan-003",
    employeeId: "emp-003",
    employeeName: "Vanna Pich",
    department: "Sales",
    amount: 500,
    reason: "Family emergency",
    requestDate: "2026-02-10",
    status: "rejected",
    riskScore: 42,
    riskLevel: "high",
    repaymentMonths: 2,
    monthlyDeduction: 250,
    remainingBalance: 500,
  },
  {
    id: "loan-004",
    employeeId: "emp-005",
    employeeName: "Chenda Mao",
    department: "HR",
    amount: 600,
    reason: "Education expense",
    requestDate: "2026-02-20",
    status: "pending",
    riskScore: 55,
    riskLevel: "medium",
    repaymentMonths: 3,
    monthlyDeduction: 200,
    remainingBalance: 600,
  },
  {
    id: "loan-005",
    employeeId: "emp-004",
    employeeName: "Leap Seng",
    department: "Finance",
    amount: 1500,
    reason: "Vehicle repair",
    requestDate: "2026-01-05",
    status: "approved",
    riskScore: 92,
    riskLevel: "low",
    repaymentMonths: 5,
    monthlyDeduction: 300,
    remainingBalance: 1200,
    approvedDate: "2026-01-05",
    approvedBy: "System (Auto-Approved)",
  },
  {
    id: "loan-006",
    employeeId: "emp-006",
    employeeName: "Srey Neth",
    department: "Engineering",
    amount: 400,
    reason: "Utility bills",
    requestDate: "2026-03-01",
    status: "pending",
    riskScore: 60,
    riskLevel: "medium",
    repaymentMonths: 2,
    monthlyDeduction: 200,
    remainingBalance: 400,
  },
  {
    id: "loan-007",
    employeeId: "emp-008",
    employeeName: "Raksa Tep",
    department: "Sales",
    amount: 700,
    reason: "Personal emergency",
    requestDate: "2026-02-28",
    status: "rejected",
    riskScore: 35,
    riskLevel: "high",
    repaymentMonths: 3,
    monthlyDeduction: 233.33,
    remainingBalance: 700,
  },
  {
    id: "loan-008",
    employeeId: "emp-007",
    employeeName: "Sophal Rin",
    department: "Operations",
    amount: 2000,
    reason: "Home renovation",
    requestDate: "2025-11-20",
    status: "completed",
    riskScore: 95,
    riskLevel: "low",
    repaymentMonths: 6,
    monthlyDeduction: 333.33,
    remainingBalance: 0,
    approvedDate: "2025-11-20",
    approvedBy: "System (Auto-Approved)",
  },
];

// ── Transactions ─────────────────────────────────────────────
export const mockTransactions: Transaction[] = [
  {
    id: "txn-001",
    employeeId: "emp-001",
    type: "salary",
    amount: 3500,
    date: "2026-02-28",
    description: "February 2026 salary",
    balanceAfter: 4700,
  },
  {
    id: "txn-002",
    employeeId: "emp-001",
    type: "deduction",
    amount: -333.33,
    date: "2026-02-28",
    description: "Loan repayment - loan-001",
    balanceAfter: 4366.67,
  },
  {
    id: "txn-003",
    employeeId: "emp-001",
    type: "advance",
    amount: -1000,
    date: "2025-12-01",
    description: "Salary advance approved",
    balanceAfter: 200,
  },
  {
    id: "txn-004",
    employeeId: "emp-001",
    type: "salary",
    amount: 3500,
    date: "2026-01-31",
    description: "January 2026 salary",
    balanceAfter: 1200,
  },
  {
    id: "txn-005",
    employeeId: "emp-002",
    type: "salary",
    amount: 2800,
    date: "2026-02-28",
    description: "February 2026 salary",
    balanceAfter: 3600,
  },
  {
    id: "txn-006",
    employeeId: "emp-002",
    type: "deduction",
    amount: -200,
    date: "2026-02-28",
    description: "Loan repayment - loan-002",
    balanceAfter: 3400,
  },
  {
    id: "txn-007",
    employeeId: "emp-002",
    type: "advance",
    amount: -800,
    date: "2026-01-15",
    description: "Salary advance approved",
    balanceAfter: 800,
  },
  {
    id: "txn-008",
    employeeId: "emp-004",
    type: "salary",
    amount: 3000,
    date: "2026-02-28",
    description: "February 2026 salary",
    balanceAfter: 5100,
  },
  {
    id: "txn-009",
    employeeId: "emp-004",
    type: "advance",
    amount: -1500,
    date: "2026-01-05",
    description: "Salary advance approved",
    balanceAfter: 2100,
  },
  {
    id: "txn-010",
    employeeId: "emp-004",
    type: "deduction",
    amount: -300,
    date: "2026-02-28",
    description: "Loan repayment - loan-005",
    balanceAfter: 4800,
  },
  {
    id: "txn-011",
    employeeId: "emp-007",
    type: "salary",
    amount: 3800,
    date: "2026-02-28",
    description: "February 2026 salary",
    balanceAfter: 7000,
  },
  {
    id: "txn-012",
    employeeId: "emp-005",
    type: "salary",
    amount: 2600,
    date: "2026-02-28",
    description: "February 2026 salary",
    balanceAfter: 3200,
  },
  {
    id: "txn-013",
    employeeId: "emp-006",
    type: "salary",
    amount: 1800,
    date: "2026-02-28",
    description: "February 2026 salary",
    balanceAfter: 2000,
  },
  {
    id: "txn-014",
    employeeId: "emp-003",
    type: "salary",
    amount: 2200,
    date: "2026-02-28",
    description: "February 2026 salary",
    balanceAfter: 2550,
  },
  {
    id: "txn-015",
    employeeId: "emp-008",
    type: "salary",
    amount: 3200,
    date: "2026-02-28",
    description: "February 2026 salary",
    balanceAfter: 3650,
  },
];

// ── Salary Records ───────────────────────────────────────────
export const mockSalaryRecords: SalaryRecord[] = mockEmployees.map((emp) => ({
  id: `sal-${emp.id}`,
  employeeId: emp.id,
  employeeName: emp.name,
  department: emp.department,
  baseSalary: emp.salary,
  deductions: mockLoans
    .filter(
      (l) =>
        l.employeeId === emp.id &&
        (l.status === "repaying" || l.status === "approved"),
    )
    .reduce((sum, l) => sum + l.monthlyDeduction, 0),
  netSalary:
    emp.salary -
    mockLoans
      .filter(
        (l) =>
          l.employeeId === emp.id &&
          (l.status === "repaying" || l.status === "approved"),
      )
      .reduce((sum, l) => sum + l.monthlyDeduction, 0),
  month: "March 2026",
  status: "pending" as const,
}));

// ── Analytics ────────────────────────────────────────────────
export const mockAnalytics: AnalyticsData = {
  totalEmployees: mockEmployees.length,
  totalLoansIssued: mockLoans.filter((l) => l.status !== "rejected").length,
  totalOutstanding: mockLoans
    .filter((l) => l.status === "repaying" || l.status === "approved")
    .reduce((sum, l) => sum + l.remainingBalance, 0),
  averageRiskScore: Math.round(
    mockEmployees.reduce((sum, e) => sum + e.riskScore, 0) /
      mockEmployees.length,
  ),
  approvalRate: Math.round(
    (mockLoans.filter((l) => l.status !== "rejected" && l.status !== "pending")
      .length /
      mockLoans.length) *
      100,
  ),
  repaymentRate: 94,
  monthlyLoanVolume: [
    { month: "Sep", amount: 2200, count: 3 },
    { month: "Oct", amount: 3100, count: 4 },
    { month: "Nov", amount: 2800, count: 3 },
    { month: "Dec", amount: 1800, count: 2 },
    { month: "Jan", amount: 3500, count: 4 },
    { month: "Feb", amount: 2400, count: 3 },
  ],
  riskDistribution: [
    { level: "Low Risk (80-100)", count: 3 },
    { level: "Medium Risk (50-79)", count: 3 },
    { level: "High Risk (0-49)", count: 2 },
  ],
  departmentLoans: [
    { department: "Engineering", amount: 2400 },
    { department: "Marketing", amount: 800 },
    { department: "Finance", amount: 1500 },
    { department: "Sales", amount: 1200 },
    { department: "HR", amount: 600 },
    { department: "Operations", amount: 2000 },
  ],
  recentActivity: [
    {
      date: "2026-03-04",
      description: "Srey Neth submitted a loan request for $400",
      type: "request",
    },
    {
      date: "2026-03-03",
      description: "Chenda Mao's loan request pending review",
      type: "pending",
    },
    {
      date: "2026-03-01",
      description: "Monthly salary processed for 8 employees",
      type: "salary",
    },
    {
      date: "2026-02-28",
      description: "Raksa Tep's loan request rejected (low score)",
      type: "rejected",
    },
    {
      date: "2026-02-20",
      description: "Dara Kim's loan repayment deducted - $200",
      type: "deduction",
    },
  ],
};
